### ISSUE TITLE
Config for Caddy proxy

### ISSUE THREAD

**Issue by magic-debian** [NoelDeMartin/nextcloud#1]
If you have a Caddy proxy container this was my setup:

compose.yaml:
``` 
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/home/user/data/ncdata
      - NEXTCLOUD_MOUNT=/home/user/data
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed
```

` data/` folder is in my home and i followed the same commands in the production setup. 

Caddy file:

```
https://nextcloud.domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
```

started the docker with the classic `docker compose up -d`

I hope this can help someone else.

I did try to follow this very well explained tutorial: https://www.blunix.com/blog/howto-install-nextcloud-on-ubuntu-2204-with-hetzner.html#installing-nextcloud-mounting-data-disk-storage-box - but i would get an access error.
